version: '3.8'

services:
  app:
    image: chatvector-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATASTORE: qdrant
      OPENAI_API_KEY: 
      BEARER_TOKEN: 
      QDRANT_URL: 
      QDRANT_API_KEY: 
      RPUNCT_LANG: en
      RPUNCT_USE_CUDA: 'False'
      PORT: ${PORT:-8080}
      WEBSITES_PORT: ${WEBSITES_PORT:-8080}
    ports:
      - "${PORT:-8080}:${WEBSITES_PORT:-8080}"
    command: ["sh", "-c", "uvicorn server.main:app --host 0.0.0.0 --port ${PORT:-${WEBSITES_PORT:-8080}}"]
